// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Provides the default [FirebaseOptions] for initializing Firebase
/// across different platforms.
///
/// Example usage:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  /// Returns the Firebase configuration based on the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux. '
          'Run the FlutterFire CLI again to generate configuration.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ================= WEB CONFIG =================
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw7ZwrXPeIS1jeBbp1MeB1iDKYKw4dE5E',
    appId: '1:318507887937:web:c7b6bb2e94dc8caa5b05c0',
    messagingSenderId: '318507887937',
    projectId: 'rollio-mobile-sprint2',
    authDomain: 'rollio-mobile-sprint2.firebaseapp.com',
    storageBucket: 'rollio-mobile-sprint2.firebasestorage.app',
  );

  // ================= ANDROID CONFIG =================
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX5JO8GQebsRab8bmTBR-iY2GKDDt1j18',
    appId: '1:318507887937:android:16a0eb9c62ebd3105b05c0',
    messagingSenderId: '318507887937',
    projectId: 'rollio-mobile-sprint2',
    storageBucket: 'rollio-mobile-sprint2.firebasestorage.app',
  );

  // ================= IOS CONFIG =================
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7oNed8Ob_nI7ObuIo7ukLiXV5fccHyG0',
    appId: '1:318507887937:ios:cbb8a9b4b7654a8a5b05c0',
    messagingSenderId: '318507887937',
    projectId: 'rollio-mobile-sprint2',
    storageBucket: 'rollio-mobile-sprint2.firebasestorage.app',
    iosBundleId: 'com.example.rollioMobile',
  );

  // ================= MACOS CONFIG =================
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7oNed8Ob_nI7ObuIo7ukLiXV5fccHyG0',
    appId: '1:318507887937:ios:cbb8a9b4b7654a8a5b05c0',
    messagingSenderId: '318507887937',
    projectId: 'rollio-mobile-sprint2',
    storageBucket: 'rollio-mobile-sprint2.firebasestorage.app',
    iosBundleId: 'com.example.rollioMobile',
  );

  // ================= WINDOWS CONFIG =================
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw7ZwrXPeIS1jeBbp1MeB1iDKYKw4dE5E',
    appId: '1:318507887937:web:df3ec569b7a3a75b5b05c0',
    messagingSenderId: '318507887937',
    projectId: 'rollio-mobile-sprint2',
    authDomain: 'rollio-mobile-sprint2.firebaseapp.com',
    storageBucket: 'rollio-mobile-sprint2.firebasestorage.app',
  );
}