// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw7ZwrXPeIS1jeBbp1MeB1iDKYKw4dE5E',
    appId: '1:318507887937:web:c7b6bb2e94dc8caa5b05c0',
    messagingSenderId: '318507887937',
    projectId: 'rollio-mobile-sprint2',
    authDomain: 'rollio-mobile-sprint2.firebaseapp.com',
    storageBucket: 'rollio-mobile-sprint2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX5JO8GQebsRab8bmTBR-iY2GKDDt1j18',
    appId: '1:318507887937:android:16a0eb9c62ebd3105b05c0',
    messagingSenderId: '318507887937',
    projectId: 'rollio-mobile-sprint2',
    storageBucket: 'rollio-mobile-sprint2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7oNed8Ob_nI7ObuIo7ukLiXV5fccHyG0',
    appId: '1:318507887937:ios:cbb8a9b4b7654a8a5b05c0',
    messagingSenderId: '318507887937',
    projectId: 'rollio-mobile-sprint2',
    storageBucket: 'rollio-mobile-sprint2.firebasestorage.app',
    iosBundleId: 'com.example.rollioMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7oNed8Ob_nI7ObuIo7ukLiXV5fccHyG0',
    appId: '1:318507887937:ios:cbb8a9b4b7654a8a5b05c0',
    messagingSenderId: '318507887937',
    projectId: 'rollio-mobile-sprint2',
    storageBucket: 'rollio-mobile-sprint2.firebasestorage.app',
    iosBundleId: 'com.example.rollioMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw7ZwrXPeIS1jeBbp1MeB1iDKYKw4dE5E',
    appId: '1:318507887937:web:df3ec569b7a3a75b5b05c0',
    messagingSenderId: '318507887937',
    projectId: 'rollio-mobile-sprint2',
    authDomain: 'rollio-mobile-sprint2.firebaseapp.com',
    storageBucket: 'rollio-mobile-sprint2.firebasestorage.app',
  );
}
